### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by coder-stas** [CanineGray/Grays-CASM-mobs#3]
Some elements of the model are not displayed correctly - the effect of "Z-fighting" is visible. Minecraft 1.18.2 + OptiFine_1.18.2_HD_U_H7 (shaders are disabled, only resource pack "Gray's+CASM+Mobs+1.18+v3.8" is used). For example, a wolf looks like this:

![01](https://user-images.githubusercontent.com/75539741/180104493-a15bcf01-ff05-4763-a80c-30762656ef37.jpg)

I've separated the problematic elements:

![02](https://user-images.githubusercontent.com/75539741/180104494-6c3d7bd7-8abb-472a-be29-4df1e66e4ad5.jpg)

I was looking for what they have in common. As it turned out, this is the scale of the texture. Where the "Z-fighting" effect is visible, the scale is not an integer.

![03](https://user-images.githubusercontent.com/75539741/180104495-84be09b0-0e8f-44d2-bbed-6338bd019970.jpg)

If you make a texture where the scale is an integer, the problem disappears.

![04](https://user-images.githubusercontent.com/75539741/180104496-154a11d2-7d93-4f18-b1f1-009d8dba71bd.jpg)

![05](https://user-images.githubusercontent.com/75539741/180104490-23c68fb4-1099-4179-98dc-9547df42533e.jpg)

Is it possible to fix all models in this way?

**Comment by CanineGray** [comment]
Well it may be an issue on your side, the pack has a lot of Z-fighting issues I've come to find. I think it has to do with anti-aliasing, but been unable to recreate the issues people have had like outlining parts not currently used or z-fighting. The only fix I can think is to go in and change each texture to be properly spread apart and scaled, but it might take a while to fix well over a hundred textures.
